### ISSUE TITLE
Blocking UI

### ISSUE THREAD

**Issue by carrbrpoa** [vakrilov/native-script-accelerometer#8]
Does it blocks UI? My app seems to freeze when I start accelerometer, even with highest delay. And I'm not able to use it from worker because of https://github.com/vakrilov/native-script-accelerometer/issues/7.

**Comment by vakrilov** [comment]
Apart from using the biggest delay and making sure you are not doing some computationally havy stuff in the callback, there is not much you can do - javascript is sync in nature, so executing the callback will block the UI. You an try to implement debouncing if you **do** have to CPU intensive work in the callback.

About #7 - I have changed the implementation to use application context instead of `foregroundActivity`. This should be available in workers as well.
