### ISSUE TITLE
Potential improvement

### ISSUE THREAD

**Issue by surdu** [vakrilov/native-script-accelerometer#9]
In [this code here](https://github.com/vakrilov/native-script-accelerometer/blob/9df72875408296b8924ff4c9e4125f5c3e9a54fe/index.android.ts#L33), wouldn't be better if instead of throwing an error the code would just return ? I don't understand why it needs to be so drastic about calling `startAccelerometerUpdates` twice.

This will avoid having that pesky `isListening` flag in the main code.

**Comment by josephcantrell14** [comment]
Please fix because if it throws an error then I must check if it is listening from my code as well.

**Comment by vakrilov** [comment]
I've just published `nativescript-accelerometer@3.0.0`.  I've changed the `start()` and `stop()` methods to no longer throw error because of current listening status.

**Note:** Calling `startAccelerometerUpdates()` when there is already a listener will stop it and start a new one. Reason: [There is a guidance in IOS to have only one `CMMotionManager`](https://developer.apple.com/documentation/coremotion/cmmotionmanager).
